kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: peaceiris/hugo:v0.65.3-mod
    commands:
      - hugo --gc --minify   # génère ./public

  - name: deploy-s3
    image: plugins/s3-sync:1
    settings:
      bucket: bucket-drone
      region: us-east-1
      source: public
      target: /
      delete: true
      acl: public-read
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key

trigger:
  branch:
    - master
  event:
    - push
    - custom

