kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: peaceiris/hugo:v0.65.3-mod
    commands:
      - hugo --gc --minify   # génère ./public

  - name: deploy-s3
    image: plugins/s3-sync:1
    settings:
      bucket: bucket-drone-release
      region: us-east-1
      source: public
      target: /
      delete: true
      acl: public-read
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
    when:
      # Déploie si tag = "release" OU si promote target = "release"
      # 1) Tag:
      event:
        include: [ tag, promote ]
      ref:
        include: [ refs/tags/release ]   # ne s'applique qu'au cas event=tag
      target:
        include: [ release ]              # ne s'applique qu'au cas event=promote

trigger:
  branch:
    - master
  event:
    - push
    - tag
    - promote
    - custom   # (utile si tu déclenches un build via l'API)

